### ISSUE TITLE
how to train the model from new dataset 

### ISSUE THREAD

**Issue by yipukangda** [d05943006/MSRCall#2]
hi,

I have created a new training dataset and want to generate a new mode mean to some special spices, I tried made training and testing dataset (.npy files) with `generate_dataset/train_data.py` script from *fast5 files* and training model with the cmd:
```
python ./MSRCall/adam_ctc_train.py \
-save_model model_out \
-train_signal_path train/train_data_signal -train_label_path train/train_data_label  \
-test_signal_path test/test_data_signal -test_label_path  test/test_data_label  -n_head 12
```

Then get the following error massage:

```
Traceback (most recent call last):
  File "./MSRCall/adam_ctc_train.py", line 464, in <module>
    main()
  File "./MSRCall/adam_ctc_train.py", line 458, in main
    train(model=model,
  File "./MSRCall/adam_ctc_train.py", line 246, in train
    batch = train_provider.next()
  File "./MSRCall/generate_dataset/train_dataloader.py", line 59, in next
    signal, label = self.dataiter.next()
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'
```
What is the mal-operation in my process?

Thanks

**Comment by d05943006** [comment]
Sorry for the late reply.
You can reproduce the training process by: 
`python MSRCall_train.py -save_model ${modelName} -as ${train_set_dir}/signals/ -al ${train_set_dir}/labels/ -es ${val_set_dir}/signals/ -el ${val_set_dir}/labels/`
As for the training/validation set generation, I follow the same procedures used in the SACall.
You can refer to [scripts for training set in SACall](https://github.com/huangnengCSU/SACall-basecaller/blob/master/scripts/KP_generate_dataset.sh) and  [scripts for validation set in SACall](https://github.com/huangnengCSU/SACall-basecaller/blob/master/scripts/KP_generate_validation_dataset.sh).
