### ISSUE TITLE
How to obtain the accuracy of each dataset with provided scripts?

### ISSUE THREAD

**Issue by HanielF** [d05943006/MSRCall#3]
Thanks for your contribution to basecalling method!

I want to know how to calculate the accuracy using the script you provided in the folder `scripts`?

**Comment by d05943006** [comment]
You can compare the called reads with reference sequence using minimap2. For example:
`minimap2 -x map-ont -c ${refPath} MSRCall_out/call.fasta > ${pafName}`
Then, use read_length_identity.py to calculate accuracies for every reads:
`python scripts/read_length_identity.py MSRCall_out/call.fasta ${pafName} > ${csvName}`
Finally, you can take median across read accuracies in the ${csvName} file.

**Comment by HanielF** [comment]
Thanks for your help!

**Comment by HanielF** [comment]
Another kind request, could you upload a `readme` about all the scripts used, I am really confused about so many scripts😭, except several scripts which start with `KP_`.

**Comment by d05943006** [comment]
Those scripts mainly come from SACall.
You can refer to their original code [here](https://github.com/huangnengCSU/SACall-basecaller/tree/master/scripts).
However, there’s no descriptions, either.💔

**Comment by HanielF** [comment]
Thanks very much!
It's really a pity that there is no readme for those scripts, I think I will take some more time studying the source code.
